server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    url: jdbc:mysql://localhost:3306/atguigu_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.chien.springcloud.entities
eureka:
  client:
    # 表示是否将自己注册到eurekaServer中，默认true
    register-with-eureka: true
    # 表示是否从eurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
